development:
  adapter: postgresql
  encoding: unicode
  database: project_planner_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: project_planner_test
  pool: 5
  username:
  password:
